### ISSUE TITLE
Versions 1.1.0 and 1.1.1 crash when run on Pi 400 model

### ISSUE THREAD

**Issue by Station010** [driver1998/PiMon#2]
Hi, running WOR with windows insider version 21322 and UEFI v1.24 on a Raspberry Pi 400
Version 1.0.5 works OK but versions 1.1.0 and 1.1.1 both show icon in sys tray then when mouse over the icon disappears
The application event log for version 1.1.1 shows -

Log Name:      Application
Source:        Application Error
Date:          27/02/2021 16:17:34
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      RaspberryPi400
Description:
Faulting application name: PiMon.exe, version: 1.1.1.0, time stamp: 0x5f66425c
Faulting module name: PiMon.exe, version: 1.1.1.0, time stamp: 0x5f66425c
Exception code: 0xc000041d
Fault offset: 0x0000000000001b64
Faulting process ID: 0x167c
Faulting application start time: 0x01d70d240d022b5f
Faulting application path: C:\Users\Pi\Downloads\PiMon\PiMon.exe
Faulting module path: C:\Users\Pi\Downloads\PiMon\PiMon.exe
Report ID: 69bc913f-df09-4e70-9d7b-2d1cd1ad50ad
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-02-27T16:17:34.6772944Z" />
    <EventRecordID>327</EventRecordID>
    <Correlation />
    <Execution ProcessID="7052" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>RaspberryPi400</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PiMon.exe</Data>
    <Data>1.1.1.0</Data>
    <Data>5f66425c</Data>
    <Data>PiMon.exe</Data>
    <Data>1.1.1.0</Data>
    <Data>5f66425c</Data>
    <Data>c000041d</Data>
    <Data>0000000000001b64</Data>
    <Data>167c</Data>
    <Data>01d70d240d022b5f</Data>
    <Data>C:\Users\Pi\Downloads\PiMon\PiMon.exe</Data>
    <Data>C:\Users\Pi\Downloads\PiMon\PiMon.exe</Data>
    <Data>69bc913f-df09-4e70-9d7b-2d1cd1ad50ad</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by driver1998** [comment]
Can you test hwmon at https://Github.com/driver1998/rpi3win10demos and see if that works? That would help narrowing down the problem.

**Comment by Station010** [comment]
I don't have an environment to build the hwmon tool and I don't see a binary download for the item.
Just a thought, on having a quick scan of the source I notice that the working version (V1.0.5) appears to handle
unknown board type by returning the string unknown, however the latest 2 versions which crash does not appear
to contain this option.
Could this unhandled situation be the issue ? and might it be as simple as adding the detection of the new board type
for Raspberry Pi 400 ?

addition: Just had a chance to compare the output of V1.0.5 with V 1.1.1 running on a Pi 4B and see that the latest version
has additional values included , namely HEVC, EMMC2, M2Mc and PIXEL_BVB so these could also be a root cause of the issue
on a Pi 400, Sorry if this is a bit vague but I have limited ability to do detailed debugging on this, however  am happy to
assist where I can

**Comment by Station010** [comment]
I have been able to install VS 2019 and build the hwmon exe
It runs without error and gives all the output expected in a CMD window.

**Comment by Station010** [comment]
To fix this crash I did the following code changes .....

In data.h I amended table to the following (to add Pi 400)

enum RpiModel {
	MODEL_UNKNOWN  = 0,
	MODEL_A        = 1,
	MODEL_B        = 2,
	MODEL_A_PLUS   = 3,
	MODEL_B_PLUS   = 4,
	MODEL_2B       = 5,
	MODEL_CM1      = 6,
	MODEL_3B       = 7,
	MODEL_ZERO     = 8,
	MODEL_CM3      = 9,
	MODEL_ZERO_W   = 10,
	MODEL_3B_PLUS  = 11,
	MODEL_3A_PLUS  = 12,
	MODEL_CM3_PLUS = 13,
	MODEL_4B       = 14,
        MODEL_PI400    = 15,

in data.c I changed table to (also to add Pi 400)

static const wchar_t* RpiModelName[] = {
    [MODEL_A]        = L"Raspberry Pi Model A",
    [MODEL_B]        = L"Raspberry Pi Model B",
    [MODEL_A_PLUS]   = L"Raspberry Pi Model A+",
    [MODEL_B_PLUS]   = L"Raspberry Pi Model B+",
    [MODEL_2B]       = L"Raspberry Pi 2 Model B",
    [MODEL_CM1]      = L"Raspberry Pi Compute Module 1",
    [MODEL_3B]       = L"Raspberry Pi 3 Model B",
    [MODEL_ZERO]     = L"Raspberry Pi Zero",
    [MODEL_CM3]      = L"Raspberry Pi Compute Module 3",
    [MODEL_ZERO_W]   = L"Raspberry Pi Zero W",
    [MODEL_3B_PLUS]  = L"Raspberry Pi 3 Model B+",
    [MODEL_3A_PLUS]  = L"Raspberry Pi 3 Model A+",
    [MODEL_CM3_PLUS] = L"Raspberry Pi Compute Module 3+",
    [MODEL_4B]       = L"Raspberry Pi 4 Model B",
    [MODEL_PI400]    = L"Raspberry Pi 400"
};

and also changed the board lookup function to identify Pi 400 model

enum RpiModel GetPiModel(ULONG BoardRevision)
{
    // www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md
    ULONG modelId = (BoardRevision >> 4) & 0xFF;

    switch (modelId) {
    case 0x00:
        return MODEL_A;
    case 0x01:
        return MODEL_B;
    case 0x02:
        return MODEL_A_PLUS;
    case 0x03:
        return MODEL_B_PLUS;
    case 0x04:
        return MODEL_2B;
    case 0x06:
        return MODEL_CM1;
    case 0x08:
        return MODEL_3B;
    case 0x09:
        return MODEL_ZERO;
    case 0x0A:
        return MODEL_CM3;
    case 0x0C:
        return MODEL_ZERO_W;
    case 0x0D:
        return MODEL_3B_PLUS;
    case 0x0E:
        return MODEL_3A_PLUS;
    case 0x10:
        return MODEL_CM3_PLUS;
    case 0x11:
        return MODEL_4B;
    case 0x13:
        return MODEL_PI400;
    default:
        return MODEL_UNKNOWN;
    }
}

Once the PI 400 model is identified the program does not crash as before.
maybe these changes ca be integrated into a new version 1.2 and made available once tested more widely.

**Comment by Station010** [comment]
Looking at why an unknown model appears to crash the code I think that there is a need for an entry
in the data.c table to handle this condition e.g.

[MODEL_UNKNOWN] = L"Unknown Model"
