### ISSUE TITLE
PiMon API

### ISSUE THREAD

**Issue by PatcherMustermann** [driver1998/PiMon#7]
Is it possible in the future to integrate an API (x86 DLL, TCP/IP, or similar) to your PiMon software?

Background: I would like to display the PiMon values in my own Smart Home HMI.

Thanks for your help!

**Comment by driver1998** [comment]
PiMon get its values via IOCTLs to the RPIQ driver, the code is in `data.c`.

**Comment by PatcherMustermann** [comment]
Sorry for the late reply and thank you for your information. Worked fine :)
